dist/index.js
package-lock.json
package.json

update packages whose `npm outdated` output is red.
- @actions/core
- @types/node
- @typescript-eslint/parser
- axios
- ts-jest
- typescript
ref #43 
keep @octokit/rest version because updates causes some errors.

update outdated dependencies(red) except for @octokit/rest

---

package-lock.json
package.json

update packages whose npm outdated output is yellow.
- @types/node
- @zeit/ncc
- jest-circus
- ts-jest
ref #43

update outdated dependencies(yellow) except for @actions/github, eslint-plugin-*

---

dist/index.js
package-lock.json
package.json

before
```
$ npm outdated
Package                    Current   Wanted   Latest  Location
@octokit/rest              16.43.1  16.43.1   17.6.0  npm-audit-action
@types/jest                 25.1.4   25.2.1   25.2.1  npm-audit-action
@types/node                 13.9.5  13.13.4  13.13.4  npm-audit-action
@typescript-eslint/parser   2.25.0   2.30.0   2.30.0  npm-audit-action
@zeit/ncc                   0.22.0   0.22.1   0.22.1  npm-audit-action
graphql                     14.6.0   14.6.0   15.0.0  npm-audit-action
jest                        25.2.3   25.5.2   25.5.2  npm-audit-action
jest-circus                 25.2.3   25.5.2   25.5.2  npm-audit-action
prettier                     2.0.2    2.0.5    2.0.5  npm-audit-action
ts-jest                     25.2.1   25.4.0   25.4.0  npm-audit-action …
```

npm update dependencies

---

README.md
__tests__/issue.test.ts
action.yml
dist/index.js
src/issue.ts
src/main.ts

This PR adds a `dedupe_issues` parameter which, when set to `true`, will cause the action to comment on an existing open issue instead of creating a new issue.
Example output: https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/issues/68
Closes https://github.com/oke-py/npm-audit-action/issues/60

Support de-duping issues

---

README.md
__tests__/audit.test.ts
__tests__/main.test.ts
__tests__/testdata/workdir/package-lock.json
__tests__/testdata/workdir/package.json
action.yml
src/audit.ts
src/main.ts

Adding the config option to run npm audit with the --production flag.
Contributes to: #74
Signed-off-by: Stelios Gkiokas <s_giokas@hotmail.com>

feat: add the ability to run with '--production'

---

README.md
__tests__/audit.test.ts
__tests__/main.test.ts
__tests__/testdata/audit/error.json
action.yml
dist/index.js
src/audit.ts
src/main.ts

This commit:
- adds the config option to run npm audit with the `--json` flag
- adds the ability to output the result of the `npm audit`
Contributes to: #76
Contributes to: #77 
Signed-off-by: Stelios Gkiokas s_giokas@hotmail.com

feat: add the ability to run with '--json' and output the result

---

dist/index.js
package-lock.json

before
```
npm outdated
Package                     Current    Wanted   Latest  Location                                Depended by
@actions/core                 1.2.6     1.2.7    1.2.7  node_modules/@actions/core              npm-audit-action
@octokit/rest               18.0.12    18.5.3   18.5.3  node_modules/@octokit/rest              npm-audit-action
@types/jest                 26.0.19   26.0.23  26.0.23  node_modules/@types/jest                npm-audit-action
@types/node                14.14.20  14.14.43   15.0.1  node_modules/@types/node                npm-audit-action
@typescript-eslint/parser    4.12.0    4.22.0   4.22.0  node_modules/@typescript-eslint/parser  npm-audit-action
eslint                       7.17.0    7.25.0   7.25.0  node_modules/eslint …
```

chore: run `npm update`

---

README.md

It was correctly `github_token` in the code and examples, but it was shown as `token` in the docs.

Fix name of `github_token` parameter

---

.github/workflows/daily.yml
.github/workflows/test.yml
dist/index.js
src/audit.ts

- _This commit is to fix an issue when running the 'npm-audit-action' on the 'windows-latest'_
- _Integrated the 'spawnSync' to use the right 'npm' script based upon the OS used_
_Note - Associated [Issue](https://github.com/oke-py/npm-audit-action/issues/123) with specified Issue identified when running the 'npm-audit-action' on a Window OS_

Fix Commit - Committing fix whereby NPM Audit Actions Fails when running on Window OS

---

.github/workflows/test.yml

ref https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

chore(test): end of support for node v16

---

package-lock.json

```
$ npm audit
graphql  16.3.0 - 16.8.0
Severity: moderate
graphql Uncontrolled Resource Consumption vulnerability - https://github.com/advisories/GHSA-9pv7-vfvm-6vr7
fix available via `npm audit fix`
node_modules/graphql
semver  6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/@babel/core/node_modules/semver
node_modules/@babel/helper-compilation-targets/node_modules/semver
node_modules/eslint-plugin-jsx-a11y/node_modules/semver
node_modules/istanbul-lib-instrument/node_modules/semver …
```

chore(package): npm audit fix

---

.github/workflows/test.yml
action.yml
package-lock.json
package.json

This PR updates the project to be compatible with Node.js 20.
Node.js 16 has reached End of Life (EOL), so we need to upgrade to a supported version. This PR updates the project to use Node.js 20, which is the latest version available as a runner for GitHub Actions.
1. Updated package.json:
- Added `engines` field with Node.js version requirement `>=20.0.0`
- Updated `@types/node` to version `^20.0.0`
2. Updated GitHub workflow file (.github/workflows/test.yml):
- Changed Node.js version from 18 to 20 for all jobs
3. Updated action.yml:
- Changed `runs.using` value from `'node16'` to `'node20'`
4. Updated package-lock.json:
- Ran `npm install` to update dependencies
Verified that GitHub workflows run successfully with these changes.

Update to Node.js 20 compatibility

---

.github/workflows/test.yml

Fix #208 
This pull request addresses an issue where the Windows build job in the CI workflow was failing. The following changes have been made:
- Added a step to set the PowerShell execution policy to Unrestricted to ensure compatibility with npm upgrade commands.
- Included commands to install and upgrade npm on Windows environments to the latest version.
- Added comments to clarify the purpose of the Windows build job.
The Windows build job was failing due to issues with npm compatibility and execution policy restrictions in the Windows environment. These changes ensure that the build process runs smoothly across all supported operating systems.
- Improves the reliability of the CI workflow on Windows.
- Ensures consistent behavior across different environments.
The changes have been …

Fix Windows build job in CI workflow

---

__tests__/testdata/workdir/package-lock.json
__tests__/testdata/workdir/package.json

This pull request updates the dependencies in the test data to fix security vulnerabilities:
- Express: Updated from 4.18.2 to 5.1.0
- TypeScript: Updated from 3.9.7 to 5.8.3
The test data contained outdated versions of express and typescript that had known security vulnerabilities. This update ensures we're using the latest secure versions in our test environment.
This change only affects the test data and does not impact the production code. All tests continue to pass with the updated dependencies.

fix: Update express and typescript in test data to fix vulnerabilities

---

.github/workflows/test.yml

This PR temporarily disables the test-on-windows job in GitHub Actions workflow to address issues with the Windows test environment.
Changes:
- Comment out the entire test-on-windows job in .github/workflows/test.yml
- Keep all other jobs (build, build-on-windows, test) enabled
This change will help stabilize the CI pipeline while we investigate and fix the underlying issues with the Windows test environment.

Disable test-on-windows job temporarily

---

package-lock.json
package.json

This PR updates the @actions/core package from version 1.10.1 to 1.11.1.
All tests are passing successfully with the updated package.

Update @actions/core from 1.10.1 to 1.11.1

---

package-lock.json
package.json

This PR updates dependencies except node, strip-ansi and eslint-related packages.

chore: update dependencies except node, strip-ansi and eslint-related packages

---

package-lock.json
package.json

This PR removes the graphql package from devDependencies as it is no longer needed.

Remove graphql from devDependencies

---

tsconfig.json

Updated `tsconfig.json` to exclude `vitest.config.ts` from TypeScript compilation.
To prevent build failures caused by files outside the `rootDir`.
None expected.
- Ensure TypeScript builds successfully.
- Verify that `vitest.config.ts` is excluded from compilation.
Closes #224

fix(tsconfig): exclude vitest.config.ts from TypeScript compilation

---

.github/workflows/test.yml
package.json
vitest.config.ts

Limited test coverage to the `src` directory only, excluding the `lib` directory.
1. Added `include: ["src/**/*.ts"]` and `exclude: ["lib/**"]` to the coverage configuration in `vitest.config.ts`
2. Added the `--run` option to the test scripts in `package.json`
3. Updated GitHub Actions workflow to use the new test scripts

fix: limit test coverage to src directory only

---

.prettierrc.json
__tests__/audit.test.ts
__tests__/issue.test.ts
__tests__/main.test.ts
src/audit.ts
src/issue.ts
src/main.ts
src/pr.ts

Resolved the conflict between Prettier and ESLint configurations by removing the `bracketSpacing: false` setting from `.prettierrc.json`.
1. Removed `bracketSpacing: false` from `.prettierrc.json` to use the default value of `true`
2. Ran `npm run format` to update all files with the new formatting rules
3. Verified that ESLint no longer reports errors related to bracket spacing
This change ensures that Prettier and ESLint configurations are consistent, preventing formatting conflicts.

fix: resolve prettier and eslint conflict by removing bracketSpacing: false

---

.clinerules/rules.md

This pull request adds detailed instructions for creating pull requests using GitHub CLI.
1. Added detailed explanations for using the `gh pr create` command
2. Included guidance on enclosing title and body in single quotes to handle spaces and special characters
3. Added best practices for handling multi-line text in PR descriptions
4. Provided examples of formatting the body text with Markdown for better readability
To clarify project guidelines and ensure team members can create pull requests in a consistent manner.
These changes standardize the pull request creation process and encourage more readable and informative pull requests.

docs: add detailed instructions for gh pr create usage

---

.clinerules/rules.md

This pull request updates the .clinerules/rules.md file to align with the actual project configuration.
1. Updated TypeScript Configuration section:
- Added `baseUrl: "./"` and `paths` configuration which were present in tsconfig.json but missing in the documentation
2. Updated Code Formatting section:
- Removed `bracketSpacing: false` as it is not present in the actual .prettierrc.json
- Added `printWidth: 80` which is present in .prettierrc.json
- Added `parser: "typescript"` which is present in .prettierrc.json
These changes ensure that the documentation accurately reflects the actual project configuration, making it easier for developers to understand and follow the project standards.

docs: update clinerules formatting and TypeScript configuration

---

.github/workflows/daily.yml
.github/workflows/git-tag.yml
README.md
package-lock.json
package.json

This PR prepares for the release of npm-audit-action@v3.0.0 with the following changes:
1. README.md: 
- Updated `oke-py/npm-audit-action@v2` to `oke-py/npm-audit-action@v3`
2. package.json:
- Updated version from `2.4.4` to `3.0.0`
3. package-lock.json:
- Automatically updated via `npm install`
4. .github/workflows/daily.yml:
- Updated two occurrences of `oke-py/npm-audit-action@v2` to `oke-py/npm-audit-action@v3`
5. .github/workflows/git-tag.yml:
- Changed workflow name from "git tag v2" to "git tag major version"
- Changed job name from "v2" to "tag-major-version"
- Modified tagging logic to extract the major version (e.g., v3.0.0 → v3) from the release tag
- This ensures that when a GitHub Release is created, the latest commit is tagged with the appropriate major version (v3)

feat: update references from v2 to v3 for release v3.0.0

---

.clinerules/rules.md

This PR clarifies the language requirements for pull request titles and descriptions.
1. Updated the Pull Requests section in .clinerules/rules.md to explicitly state that PR titles and descriptions must be in English only, not in Japanese.
2. Added emphasis with bold formatting and explicit wording to make the requirement clearer.
This change aims to reduce confusion and ensure all team members follow the English-only policy for PR documentation.

docs: clarify PR language requirements

---

.github/workflows/daily.yml
.github/workflows/test.yml

This PR addresses the npm.cmd EINVAL errors on Windows by:
1. Disabling the scan-on-windows job in daily.yml workflow
2. Adding PowerShell execution policy settings to both Windows jobs (commented out)
When running the workflow on Windows, the following error occurs:
```
Run ./
Current working directory: D:\a\npm-audit-action\npm-audit-action
Error: spawnSync npm.cmd EINVAL
```
- Commented out the scan-on-windows job in daily.yml to prevent the workflow from failing on Windows
- Added PowerShell execution policy settings to both Windows jobs (even though they are commented out) for future reference
- The build-on-windows job in test.yml is kept as is since it runs successfully
This approach ensures the workflows run successfully while providing a template for future Windows jobs that …

fix: disable scan-on-windows job and add PowerShell execution policy setting

---

package-lock.json
package.json
rollup.config.ts
tsconfig.eslint.json

This PR migrates the build process from @vercel/ncc to Rollup for better alignment with modern bundling practices and the actions/typescript-action template.
1. Removed @vercel/ncc and added Rollup along with necessary plugins.
2. Updated package.json scripts to use Rollup for bundling.
3. Created rollup.config.ts for Rollup configuration.
4. Adjusted the build process to directly bundle TypeScript files with Rollup.
5. Updated the all script to align with the current project structure.
- Simplified build process.
- Better ES module support.
- Alignment with the actions/typescript-action template.
- The dist directory is excluded from commits as it is updated automatically by the build process.

chore: migrate build process from @vercel/ncc to rollup

---

.clinerules/rules.md
.github/workflows/dist.yml
package.json

This PR renames the npm script from "pack" to "package" and updates the CI workflow accordingly.
1. Renamed npm script from "pack" to "package" in package.json
2. Updated the "all" script to use "package" instead of "pack"
3. Updated the CI workflow job name from "pack" to "package"
4. Removed the redundant "npm run build" step from the CI workflow
5. Updated .clinerules/rules.md to reflect these changes
These changes improve consistency in the build process terminology and simplify the CI workflow by removing redundant steps.
Fixes #241

refactor(ci): rename npm script from pack to package and update workflow

---

package.json

This PR renames the npm scripts for code formatting to align with the template repository (actions/typescript-action).
1. Renamed `format` to `format:write` and updated the command to `npx prettier --write .`
2. Renamed `format-check` to `format:check` and updated the command to `npx prettier --check .`
3. Updated related scripts (`bundle` and `all`) to use the new script names
This change aligns our script naming convention with the template repository, making it more consistent and easier to understand.
- Run `npm run format:write` to verify it formats the code correctly
- Run `npm run format:check` to verify it checks the code formatting correctly
- Run `npm run bundle` and `npm run all` to verify they work with the new script names

refactor(scripts): rename format scripts to format:write and format:check

---

__fixtures__/core.ts
__tests__/main.test.ts
tsconfig.eslint.json

This PR suppresses unnecessary output during test execution.
Main changes:
1. Created `__fixtures__/core.ts` file to mock the `@actions/core` module
2. Updated test files to use the mock instead of the actual `@actions/core` module
These changes ensure that only test results are displayed during test execution, making the output cleaner and more focused.

fix: suppress unnecessary output during test execution

---

.github/workflows/test.yml

- Modified the test workflow to run Coveralls upload only on the `ubuntu-latest` runner
- This prevents duplicate coverage reports in multi-OS test environments
- Ensures consistent test reporting by running coverage upload from a single environment
- The current configuration attempts to upload coverage reports from all test environments (ubuntu-latest, windows-latest, macos-latest)
- This can lead to duplicate or conflicting coverage reports in Coveralls
- By limiting the upload to ubuntu-latest, we maintain consistent reporting while still testing across multiple platforms

fix(ci): run coveralls upload only on ubuntu-latest
