@types/octokit/index.d.ts, README.md, __tests__/main.test.ts, action.yml, package-lock.json, package.json, src/main.ts
closes #2 
closes #7 
e.g. https://github.com/oke-py/labeler-demo/issues/6
=> Open a GitHub Issue if vulnerabilities are found

.eslintrc.json, README.md, __tests__/audit.test.ts, action.yml, dist/index.js, src/audit.ts, src/main.ts
closes #6 
closes #11 
e.g. https://github.com/oke-py/labeler-demo/issues/11
=> Set Issue labels by inputs & add unit test

.github/workflows/test.yml, README.md, package-lock.json, package.json
=> Measure test coverage

.github/workflows/daily.yml, README.md
find vulnerability of this repo.
=> Execute daily scan

__tests__/issue.test.ts, dist/index.js, src/interface.ts, src/issue.ts, src/main.ts
=> add test for issue option

.github/workflows/daily.yml, README.md, __tests__/issue.test.ts, package-lock.json, package.json, src/issue.ts, src/main.ts
=> Creates an issue even if inputs.issue_labels is not given

.github/workflows/test.yml, action.yml, src/main.ts
=> Get github context from inputs

.eslintrc.json, .github/workflows/daily.yml, .github/workflows/test.yml, README.md, action.yml, dist/index.js, package-lock.json, package.json, src/audit.ts, src/issue.ts, src/main.ts, src/pr.ts
=> Create a comment on pull request when vulnerabilities are found

.github/workflows/daily.yml, DEVELOPMENT.md, __tests__/audit.test.ts, __tests__/main.test.ts, src/audit.ts
=> add unit test and cleanup

__tests__/audit.test.ts
=> Add unit test for error handling

dist/index.js, src/main.ts
=> Action fails always if vulnerabilities are found

.github/workflows/daily.yml, .github/workflows/test.yml, README.md
https://github.com/marketplace/actions/checkout
=> update actions/checkout to v2

dist/index.js, src/audit.ts
=> Action should fail if child_process causes an error

package-lock.json, package.json
executed these commands
```
npm install --save-dev eslint@6.8.0
npm audit fix
```
close #38 
close #39
=> update eslint to 6.8.0 to fix vulnerabilities

dist/index.js, package-lock.json, package.json, src/main.ts
update
- @actions/github
- @octokit/rest
ref #43
=> update @actions/github and @octokit/rest

README.md, __tests__/audit.test.ts, __tests__/main.test.ts, action.yml, dist/index.js, package.json, src/audit.ts, src/main.ts
=> filter vulnerabilities by audit_level

@types/octokit/index.d.ts, dist/index.js, package-lock.json, package.json, src/main.ts
=> update @octokit/rest from 16.43.1 to 17.9.2

.github/workflows/test.yml, README.md, __tests__/testdata/workdir/package-lock.json, __tests__/testdata/workdir/package.json, __tests__/workdir.test.ts, dist/index.js, src/main.ts, src/workdir.ts
=> support different working directory

__tests__/audit.test.ts, dist/index.js, src/audit.ts
Fix verified in https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/pull/100/checks?check_run_id=847844745
Fix #66
=> Catch errors thrown by Audit.run and increase child process buffer size

.github/workflows/daily.yml, README.md, dist/index.js, package-lock.json, package.json
=> fix dependencies' vulnerabilities

README.md, __tests__/main.test.ts, action.yml, dist/index.js, src/main.ts
=> feature: support create_issues, create_pr_comments flag

.github/workflows/daily.yml, README.md, dist/index.js, package-lock.json, package.json
=> fix CVE-2022-0235

dist/index.js, package-lock.json
=> npm audit fix to fix CVE-2022-0536

dist/index.js, package-lock.json, package.json, src/main.ts
=> Adds 'info', 'none' as a valid argument for audit-level

.github/workflows/daily.yml, .github/workflows/test.yml
example
- https://github.com/oke-py/npm-audit-action/runs/7139017734?check_suite_focus=true
ref
- https://stackoverflow.com/questions/72401421/message-npm-warn-config-global-global-local-are-deprecated-use-loc
- https://qiita.com/tatsuya_yamakawa/items/b24794290b0eceb63e06
=> update npm globally at an earlier step of each job

dist/index.js, package-lock.json, package.json
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
fix #130
=> update @actions/core not to use deprecated commands

__tests__/testdata/workdir/package-lock.json, __tests__/testdata/workdir/package.json
https://github.com/advisories/GHSA-hrpp-h998-j3pp
close #132
close #133
=> test: fix CVE-2022-24999 in testdata to avoid failure unit test

.github/workflows/test.yml
This will stop creating redundant issues.
=> test: PR build will not create a new issue to report vulnerabilities

dist/index.js, package-lock.json, package.json, src/main.ts
=> chore(package): bump typescript from 3.9.10 to 4.9.4

.github/workflows/dist.yml
=> chore(build): set up actions to automatically update dist/index.js

package-lock.json, package.json
https://github.com/actions/toolkit/blob/main/packages/github/RELEASES.md
=> chore(package): bump @actions/github from 5.0.3 to 5.1.1

.github/workflows/package-version.yml
also changed labels' name.
https://github.com/oke-py/npm-audit-action/labels
=> fix: automatically update package version

.github/workflows/test.yml
=> chore(test): run tests on node 16 & 18

__tests__/audit.test.ts, __tests__/main.test.ts, package-lock.json, package.json
=> chore(package): bump jest from 27.2.5 to 29.3.1

package-lock.json, package.json
https://github.com/octokit/rest.js/releases
=> chore(package): bump @octokit/rest from 18.12.0 to 19.0.5

.github/release.yml
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
=> [skip ci] chore(release): introduce automatically generated release notes

.github/workflows/test.yml
ref https://github.com/oke-py/npm-audit-action/pull/156
=> chore(test): ignore devDependencies vulnerabilities

package-lock.json
https://github.com/axios/axios/releases/tag/1.2.2
=> chore(package): bump axios from 1.2.1 to 1.2.2

action.yml
https://github.com/oke-py/npm-audit-action/actions/runs/3819673757/jobs/6497425927
=> docs: fix an error

.github/workflows/git-tag.yml
=> chore(release): re-target v2 tag on release

.github/workflows/git-tag.yml
https://github.com/oke-py/npm-audit-action/actions/runs/3819870937/jobs/6497766482
=> chore(release): fix error on re-targeting v2 tag on release

package-lock.json
=> chore(package): bump json5 from 1.0.1 to 1.0.2 to fix CVE-2022-46175

.devcontainer/devcontainer.json, Dockerfile
https://mcr.microsoft.com/en-us/product/devcontainers/javascript-node/about
=> chore(dev): use devcontainers/javascript-node:18

package-lock.json
```shell
npm update jest jest-circus @types/jest ts-jest eslint-plugin-jest
```
=> chore(package): bump jest from 29.3.1 to 29.5.0

package-lock.json
```shell
npm update eslint eslint-plugin-github @typescript-eslint/parser
```
=> chore(package): bump eslint from 8.30.0 to 8.38.0

package-lock.json
```shell
npm update @vercel/ncc
```
=> chore(package): bump @vercel/ncc from 0.36.0 to 0.36.1

package-lock.json
=> chore(package): bump prettier from 2.8.1 to 2.8.7

.github/workflows/daily.yml
=> create issue only when vulns found in production modules

package-lock.json, package.json
ref https://github.com/oke-py/npm-audit-action/pull/188
=> chore(deps-dev): bump graphql from 16.6.0 to 16.8.1

.github/workflows/test.yml
This PR adds descriptive names to the steps in the GitHub Actions workflow file to improve readability and maintainability.
- Added "Install dependencies and run all scripts" name to npm installation and script execution steps
- Added "Run npm audit action" name to the npm audit action execution steps
- Added "Run npm audit action in testdata workdir" name to the steps that run npm audit in the test data directory
- Improves workflow readability
- Makes it easier to understand the purpose of each step at a glance
- Helps with troubleshooting by providing clear step names in the GitHub Actions UI
=> Add step names to GitHub Actions workflow for better readability

.devcontainer/devcontainer.json
This PR updates the development container configuration:
1. Upgrade Node.js to version 20
2. Add GitHub CLI feature
3. Add Claude extension for VS Code
These changes improve the development environment by providing the latest Node.js version and additional tools for better productivity.
=> Update devcontainer.json: Node.js 20, add Claude extension, enable GitHub CLI

.clinerules/rules.md
This PR adds the .clinerules/rules.md file that defines development guidelines and best practices for our TypeScript/JavaScript projects.
Added content includes:
- TypeScript/JavaScript best practices
- Code formatting conventions
- Package management guidelines
- Testing approach
- Build process
- Git workflow (commit messages, branches, PR conventions)
- Code review standards
- CI/CD configuration
- Documentation requirements
=> docs: Add coding standards and guidelines

src/audit.ts, src/issue.ts, src/main.ts, src/pr.ts, tsconfig.json
This PR modernizes the code from ES6 to ES2020.
1. **tsconfig.json**:
- Updated compile target from  to `es6` to `es2020`
2. **audit.ts**:
- Changed `Array<string>` to `string[]` (more modern type notation)
- Changed `process.platform == 'win32'` to `process.platform === 'win32'` (stricter comparison)
- Removed unnecessary try-catch block
- Changed `result.stderr && result.stderr.length > 0` to `result.stderr?.length > 0` (using optional chaining)
3. **issue.ts**:
- Changed `iss === undefined ? null : iss.number` to `iss?.number ?? null` (using optional chaining and nullish coalescing)
4. **pr.ts**:
- Added `await` to `octokit.issues.createComment` result
5. **main.ts**:
- Improved error handling (using optional chaining and nullish coalescing)
These changes leverage ES2020 features, …
=> Modernize code to ES2020

.clinerules/rules.md
- Updated TypeScript configuration guidelines in clinerules
- Enhanced code formatting rules with more specific Prettier settings
- Added detailed instructions for consistent naming conventions
These updates provide clearer guidance for developers to maintain consistent code quality and follow project standards.
No functional changes were made, only documentation updates.
#220
=> docs(clinerules): update TypeScript config and code formatting rules

DEVELOPMENT.md
This PR adds the major version release procedure to DEVELOPMENT.md.
1. Added a Release Process section to DEVELOPMENT.md
2. Documented detailed steps for major version releases
3. Included minor and patch release procedures for reference
4. Outlined automatic processes
Particularly emphasized the importance of waiting for the dist/index.js update before creating a release.
=> docs: add major version release procedure to DEVELOPMENT.md

.clinerules/rules.md, .devcontainer/devcontainer.json, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, DEVELOPMENT.md, README.md, __tests__/testdata/audit/error.json
This PR formats code with Prettier.
- Formatted 7 files with Prettier:
- .clinerules/rules.md
- .devcontainer/devcontainer.json
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- DEVELOPMENT.md
- README.md
- __tests__/testdata/audit/error.json
These changes were made by running `npm run all` which includes the format:write script.
=> style(format): format code with Prettier

.clinerules/rules.md
Updated the TypeScript/JavaScript Best Practices section to align with the current project configuration.
1. TypeScript Configuration:
- Updated `target` from ES2020 to ES2022
- Added `moduleResolution: NodeNext`
- Changed `outDir` from "./lib" to "./dist"
- Added new settings (`type: "module"`, Node.js version 20+ requirement, `resolveJsonModule`, `forceConsistentCasingInFileNames`)
2. Code Formatting:
- Updated ESLint configuration to use the new flat config format (eslint.config.mjs)
- Explicitly mentioned TypeScript ESLint usage
- Updated formatting commands to `npm run format:write` and `npm run format:check`
3. Package Management:
- Added Node.js version requirement (>=20.0.0)
4. Testing:
- Added details about test execution commands
5. Build Process:
- Updated build process details …
=> docs: update TypeScript/JavaScript best practices
